version: "3.3"
services:
  app:
    working_dir: "/opt/stock-entity-framework"
    build:
      context: .
      dockerfile: Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "8181:8181"
    volumes:
      - type: "bind"
        source: "."
        target: "/opt/stock-entity-framework"
